# TODO: Use the official python image as base image. Use version "3.10.2-buster".
FROM ...

# TODO: Create a directory called "/app"

# TODO: Switch the context to the newly created working directory

# TODO Add the dependency file "requirements.txt" to the image

# TODO Install the Python dependencies via "pip install -r requirements.txt"
RUN ...

# TODO Ensure the code from the current folder is added to the /app directory inside the container

# TODO: Document which port is exposed by default: 80/tcp

# TODO: Default command to be run when launching the container: gunicorn
ENTRYPOINT [ "..." ]

# TODO: Default args for this image: "app:app -b 0.0.0.0:80 --log-file - --access-logfile - --workers 4 --keep-alive0"
CMD [ "...", "..." ]