name: docker-compose-actions-workflow

on:
  schedule:
    - cron: '0 8 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.GITHUB_REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        env:
          GITHUB_REGISTRY: ghcr.io
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the images
        run: docker-compose build

      - name: Push the images to the Github registry
        if: github.event_name != 'pull_request'
        run: docker-compose push

      - name: Log into docker registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Push the images to the Docker Hub
        if: github.event_name != 'pull_request'
        run: ./push-to-docker-hub.sh