name: ci

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the images
        run: |
          yes | cp solution/compose.yaml .
          yes | cp solution/vote/Dockerfile src/vote/
          docker compose build

      - name: Push the images to the Github registry
        run: docker compose push